# Generated by Django 4.2 on 2024-10-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetsOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.BooleanField()),
                ('birth', models.DateField(null=True)),
                ('color', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('pet_breed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_list.breed')),
                ('pet_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_list.petsowner')),
                ('pet_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_list.petstype')),
            ],
        ),
    ]
