# Generated by Django 4.2 on 2024-10-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_list', '0002_breed_petsowner_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.BooleanField()),
                ('birth', models.DateField(null=True)),
                ('color', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_list.breeds')),
            ],
        ),
        migrations.CreateModel(
            name='PetsOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_breed_id',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_owner_id',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type_id',
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetsOwner',
        ),
        migrations.DeleteModel(
            name='PetsType',
        ),
        migrations.AddField(
            model_name='pets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_list.petsowners'),
        ),
        migrations.AddField(
            model_name='breeds',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_list.petstypes'),
        ),
    ]
