# Generated by Django 4.2 on 2024-10-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_list', '0003_breeds_pets_petsowners_petstypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petstypes',
            options={'verbose_name': 'Тип домашнего животного', 'verbose_name_plural': 'Типы домашних животных'},
        ),
        migrations.AlterField(
            model_name='petstypes',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='petstypes',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
    ]
