# Generated by Django 5.1.3 on 2024-11-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_list', '0006_alter_pets_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
